drop type site_status, site_group_status;

create type site_status as enum ('UP', 'DOWN', 'ADDED_TO_GROUP');
create type site_group_status as enum ('ALL_UP', 'ALL_DOWN', 'PARTIAL_UP', 'NO_SITES');

drop table sites,site_groups,group_site,site_check_logs, emails, telegram_users;

create table sites (
	id bigint primary key,
	name varchar(256) not null,
	description text,
	url text not null,
	site_health_check_interval bigint not null,
	status site_status not null
);
create table site_groups (
	id bigint primary key,
	name varchar(256) not null,
	description text,
	status site_group_status default 'NO_SITES'
);
create table group_site (
	site_id bigint references sites(id),	
	group_id bigint references site_groups(id)
);
create table site_check_logs (
	id bigint primary key,
	check_time timestamp not null default now(),
	status site_status not null,
	site_id int references sites(id)
);
create table emails (
	id bigint primary key,
	address varchar(256) not null,
	verification_code varchar(256),
	code_expiration_time timestamp,
	enabled bool default false
);
create table telegram_users (
	id bigint primary key,
	username varchar(256),
	enabled bool default false,
    disabled_expiration_time timestamp
);

alter table sites alter column id add generated by default as identity;
alter table site_groups alter column id add generated by default as identity;
alter table site_check_logs alter column id add generated by default as identity;
alter table emails alter column id add generated by default as identity;

-- search script --
select s.* from sites s 
inner join group_site gs on gs.site_id=s.id
inner join site_groups sg on gs.group_id=sg.id
where lower(concat(s.name,s.description,s.url,s.site_health_check_interval,s.status))
LIKE concat('%', lower('e'), '%') and sg.id = 2 order by s.name

SELECT *
FROM site_check_logs where site_id = 66
WHERE to_char(check_time, 'YYYY-MM-DD HH24:MI:SS') LIKE '%2023-07-26%'




